export default  [
  {
      id:1,
      iconURL:"Bitcoin.png",
      cryptoName:"Bitcoin",
      abbr:"BTC",
      price:"$3,285,553.75",
      change:"+1.06%",
      marketCap:"$60.1T",
      isWatchlisted:false
  },
  {
      id:2,
      iconURL:"ethereum.png",
      cryptoName:"Ethereum",
      abbr:"ETH",
      price:"$216,678,10",
      change:"-5.49%",
      marketCap:"$25.4T",
      isWatchlisted:false
  },
  {
      id:3,
      iconURL:"tether.png",
      cryptoName:"Tether",
      abbr:"USDT",
      price:"$74.31",
      change:"+0.11%",
      marketCap:"$4.6T",
      isWatchlisted:false
  },
  {
      id:4,
      iconURL:"cardano.png",
      cryptoName:"Cardano",
      abbr:"ADA",
      price:"$104.52",
      change:"-1.82%",
      marketCap:"$3.4T",
      isWatchlisted:false
  },
  {
      id:5,
      iconURL:"xrp.png",
      cryptoName:"XRP",
      abbr:"XRP",
      price:"$57.21",
      change:"+1.11%",
      marketCap:"$2.7T",
      isWatchlisted:false
  },
  {
      id:6,
      iconURL:"Dogecoin.png",
      cryptoName:"Dodge",
      abbr:"XRP",
      price:"$17.64",
      change:"-6.96%",
      marketCap:"$2.3T",
      isWatchlisted:false
  },
  {
    id:7,
    iconURL:"USDCoin.png",
    cryptoName:"USD Coin",
    abbr:"XRP",
    price:"$74.26",
    change:"+1.01%",
    marketCap:"$2.1T",
    isWatchlisted:false
}
]